In [3]:
import pandas as pd

In [4]:
tdf=pd.read_excel(r'C:\Users\lchicco\Desktop\tdfprueba.xlsx')
tdf

,Nro AP,Posicion,Servicio,Cliente,Dia Ret Dir 1,Pto Planif Ret Dir 1,Recorrido Ret Dir 1,Horario Ret Dir 1,Dia Ent Dir 2,Pto Planif Ent Dir 2,...,Dia Ret Dir 2,Pto Planif Ret Dir 2,Recorrido Ret Dir 2,Horario Ret Dir 2,Dia Ent Dir 1,Pto Planif Ent Dir 1,Recorrido Ent Dir 1,Horario Ent Dir 1,Direccion2,Bloqueado
0,40014546,20,4001454620,Banco de Santa Cruz S.A.,5.0,A021,RGL001,16:45:00,1.0,A029,...,1.0,A029,CRD009,09:30:00,2.0,A021,RGL001,08:30:00,CALETA OLIVIA - AV. INDEPENDENCIA 1070 - CP...,NaN
1,40014598,60,4001459860,Boston Cia. Arg. de Seguros,4.0,A001,CRS024,16:00:00,1.0,A010,...,1.0,A010,MDZ01B,11:40:00,4.0,A001,CRS024,16:00:00,BOSTON (MDZ) - AV ESPAÑA 1185 - CP: 5500 -...,X
2,40014611,80,4001461180,Petersen Thiele y Cruz S.A.,2.0,A001,CRS013,17:10:00,3.0,A022,...,2.0,A022,UAQ01B,14:00:00,3.0,A001,CRS009,09:20:00,PETERSEN -UAQ- Pocito - Ruta 40 e/ calles 6 y ...,NaN
3,40014862,100,40014862100,TRANSFARMACO S.A.,1.0,A001,CRS041,16:00:00,2.0,A005,...,1.0,A005,COR027,16:50:00,2.0,A001,IRI016,08:20:00,Transfarmaco S.A. (COR) - VELEZ SARFIELD 4950 ...,NaN
4,40015273,20,4001527320,Nuevo Banco de Entre R¡os S.A.,1.0,A020,PAR017,16:40:00,2.0,A022,...,NaN,NaN,NaN,00:00:00,NaN,NaN,NaN,00:00:00,BCO SAN JUAN COMPUTOS (MM) - Av. Ignacio de la...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,40038816,600,40038816600,TOYOTA ARGENTINA S A,1.0,A001,IRI017,15:30:00,3.0,A010,...,3.0,A010,MDZ09A,16:00:00,5.0,A001,ITA006,10:00:00,Yacopini Inversora S.A. Godoy Cruz - Carril R...,NaN
13576,40038085,600,40038085600,BANCO ITAU ARGENTINA S A,4.0,A001,ITA008,19:45:00,5.0,A001,...,5.0,A001,VSF013,17:25:00,5.0,A001,ITA010,19:45:00,BCO ITAU SUC 5 BELGRANO - Av Cabildo 2215 - Be...,NaN
13577,40038088,600,40038088600,BANCO ITAU ARGENTINA S A,4.0,A001,VSF013,17:25:00,4.0,A001,...,NaN,NaN,NaN,00:00:00,NaN,NaN,NaN,00:00:00,GIRE - AV CASEROS 3568/72 - CP: 1263 - CAP...,NaN
13578,40038816,600,40038816600,TOYOTA ARGENTINA S A,2.0,A001,IRI017,15:30:00,4.0,A010,...,4.0,A010,MDZ09A,16:00:00,1.0,A001,ITA006,10:00:00,Yacopini Inversora S.A. Godoy Cruz - Carril R...,NaN
13579,40038085,600,40038085600,BANCO ITAU ARGENTINA S A,5.0,A001,ITA008,19:45:00,1.0,A001,...,1.0,A001,VSF013,17:25:00,1.0,A001,ITA010,19:45:00,BCO ITAU SUC 5 BELGRANO - Av Cabildo 2215 - Be...,NaN

In [5]:
tdff=tdf.loc[tdf['Cliente']!='ORG COURIER ARG']
tdfo=tdff.loc[tdff['Bloqueado']!='X']
tdfo

,Nro AP,Posicion,Servicio,Cliente,Dia Ret Dir 1,Pto Planif Ret Dir 1,Recorrido Ret Dir 1,Horario Ret Dir 1,Dia Ent Dir 2,Pto Planif Ent Dir 2,...,Dia Ret Dir 2,Pto Planif Ret Dir 2,Recorrido Ret Dir 2,Horario Ret Dir 2,Dia Ent Dir 1,Pto Planif Ent Dir 1,Recorrido Ent Dir 1,Horario Ent Dir 1,Direccion2,Bloqueado
0,40014546,20,4001454620,Banco de Santa Cruz S.A.,5.0,A021,RGL001,16:45:00,1.0,A029,...,1.0,A029,CRD009,09:30:00,2.0,A021,RGL001,08:30:00,CALETA OLIVIA - AV. INDEPENDENCIA 1070 - CP...,NaN
2,40014611,80,4001461180,Petersen Thiele y Cruz S.A.,2.0,A001,CRS013,17:10:00,3.0,A022,...,2.0,A022,UAQ01B,14:00:00,3.0,A001,CRS009,09:20:00,PETERSEN -UAQ- Pocito - Ruta 40 e/ calles 6 y ...,NaN
3,40014862,100,40014862100,TRANSFARMACO S.A.,1.0,A001,CRS041,16:00:00,2.0,A005,...,1.0,A005,COR027,16:50:00,2.0,A001,IRI016,08:20:00,Transfarmaco S.A. (COR) - VELEZ SARFIELD 4950 ...,NaN
4,40015273,20,4001527320,Nuevo Banco de Entre R¡os S.A.,1.0,A020,PAR017,16:40:00,2.0,A022,...,NaN,NaN,NaN,00:00:00,NaN,NaN,NaN,00:00:00,BCO SAN JUAN COMPUTOS (MM) - Av. Ignacio de la...,NaN
5,40017370,20,4001737020,Nuevo Banco de Santa Fe S.A.,3.0,A011,SFN009,01:55:00,3.0,A051,...,3.0,A051,RAF005,17:45:00,3.0,A011,SFN009,22:15:00,HUMBERTO PRIMERO - Bv. Urquiza 197 - CP: 2...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,40038816,600,40038816600,TOYOTA ARGENTINA S A,1.0,A001,IRI017,15:30:00,3.0,A010,...,3.0,A010,MDZ09A,16:00:00,5.0,A001,ITA006,10:00:00,Yacopini Inversora S.A. Godoy Cruz - Carril R...,NaN
13576,40038085,600,40038085600,BANCO ITAU ARGENTINA S A,4.0,A001,ITA008,19:45:00,5.0,A001,...,5.0,A001,VSF013,17:25:00,5.0,A001,ITA010,19:45:00,BCO ITAU SUC 5 BELGRANO - Av Cabildo 2215 - Be...,NaN
13577,40038088,600,40038088600,BANCO ITAU ARGENTINA S A,4.0,A001,VSF013,17:25:00,4.0,A001,...,NaN,NaN,NaN,00:00:00,NaN,NaN,NaN,00:00:00,GIRE - AV CASEROS 3568/72 - CP: 1263 - CAP...,NaN
13578,40038816,600,40038816600,TOYOTA ARGENTINA S A,2.0,A001,IRI017,15:30:00,4.0,A010,...,4.0,A010,MDZ09A,16:00:00,1.0,A001,ITA006,10:00:00,Yacopini Inversora S.A. Godoy Cruz - Carril R...,NaN
13579,40038085,600,40038085600,BANCO ITAU ARGENTINA S A,5.0,A001,ITA008,19:45:00,1.0,A001,...,1.0,A001,VSF013,17:25:00,1.0,A001,ITA010,19:45:00,BCO ITAU SUC 5 BELGRANO - Av Cabildo 2215 - Be...,NaN

In [12]:
tdfn=tdfo.iloc[:,[0,1,2,3]]
tdfn

         Nro AP  Posicion     Servicio                         Cliente
0      40014546        20   4001454620        Banco de Santa Cruz S.A.
2      40014611        80   4001461180     Petersen Thiele y Cruz S.A.
3      40014862       100  40014862100               TRANSFARMACO S.A.
4      40015273        20   4001527320  Nuevo Banco de Entre R¡os S.A.
5      40017370        20   4001737020    Nuevo Banco de Santa Fe S.A.
...         ...       ...          ...                             ...
13575  40038816       600  40038816600            TOYOTA ARGENTINA S A
13576  40038085       600  40038085600        BANCO ITAU ARGENTINA S A
13577  40038088       600  40038088600        BANCO ITAU ARGENTINA S A
13578  40038816       600  40038816600            TOYOTA ARGENTINA S A
13579  40038085       600  40038085600        BANCO ITAU ARGENTINA S A

[13095 rows x 4 columns]

In [13]:
t1=tdfn
t2=tdfn
t3=tdfn
t4=tdfn
frames=[t1,t2,t3,t4]
t5=pd.concat(frames,keys=['RO','ED','RD','EO'])
t5

            Nro AP  Posicion     Servicio                         Cliente
RO 0      40014546        20   4001454620        Banco de Santa Cruz S.A.
   2      40014611        80   4001461180     Petersen Thiele y Cruz S.A.
   3      40014862       100  40014862100               TRANSFARMACO S.A.
   4      40015273        20   4001527320  Nuevo Banco de Entre R¡os S.A.
   5      40017370        20   4001737020    Nuevo Banco de Santa Fe S.A.
...            ...       ...          ...                             ...
EO 13575  40038816       600  40038816600            TOYOTA ARGENTINA S A
   13576  40038085       600  40038085600        BANCO ITAU ARGENTINA S A
   13577  40038088       600  40038088600        BANCO ITAU ARGENTINA S A
   13578  40038816       600  40038816600            TOYOTA ARGENTINA S A
   13579  40038085       600  40038085600        BANCO ITAU ARGENTINA S A

[52380 rows x 4 columns]

In [30]:
tro=tdfo.iloc[:,[4,5,6,7]]
ted=tdfo.iloc[:,[8,9,10,11]]
trd=tdfo.iloc[:,[13,14,15,16]]
teo=tdfo.iloc[:,[17,18,19,20]]

In [49]:
tro['direccion']=tdfo['Direccion1']
tro.columns=['Dia','Pto Planif','Recorrido','Horario','Direccion','Tipo']
tro['Tipo']='RO'
ted['direccion']=tdfo['Direccion2']
ted.columns=['Dia','Pto Planif','Recorrido','Horario','Direccion','Tipo']
ted['Tipo']='ED'
trd['direccion']=tdfo['Direccion2']
trd.columns=['Dia','Pto Planif','Recorrido','Horario','Direccion','Tipo']
trd['Tipo']='RD'
teo['direccion']=tdfo['Direccion1']
teo.columns=['Dia','Pto Planif','Recorrido','Horario','Direccion','Tipo']
teo['Tipo']='EO'

<ipython-input-49-0db3c355bf66>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tro['direccion']=tdfo['Direccion1']
<ipython-input-49-0db3c355bf66>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tro['Tipo']='RO'
<ipython-input-49-0db3c355bf66>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ted['direccion']=tdfo['Direccion2']
<ipython-input-49-0db3c355bf66>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ted['Tipo']='ED'
<ipython-input-49-0db3c355bf66>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trd['direccion']=tdfo['Direccion2']
<ipython-input-49-0db3c355bf66>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trd['Tipo']='RD'
<ipython-input-49-0db3c355bf66>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teo['direccion']=tdfo['Direccion1']
<ipython-input-49-0db3c355bf66>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teo['Tipo']='EO'

In [41]:
frames2=[tro,ted,trd,teo]
t6=pd.concat(frames2, keys=['RO','ED','RD','EO'])
t6

          Dia Pto Planif Recorrido   Horario  \
RO 0      5.0       A021    RGL001  16:45:00
   2      2.0       A001    CRS013  17:10:00
   3      1.0       A001    CRS041  16:00:00
   4      1.0       A020    PAR017  16:40:00
   5      3.0       A011    SFN009  01:55:00
...       ...        ...       ...       ...
EO 13575  5.0       A001    ITA006  10:00:00
   13576  5.0       A001    ITA010  19:45:00
   13577  NaN        NaN       NaN  00:00:00
   13578  1.0       A001    ITA006  10:00:00
   13579  1.0       A001    ITA010  19:45:00

                                                  Direccion
RO 0      RIO GALLEGOS - Dr. Nestor C. Kirchner 812     ...
   2      Petersen Thiele y Cruz - CERRITO 740 1   - CP:...
   3      Transfarmaco S.A. (TIGRE 2) - MARCO SASTRE 108...
   4      CTRO COMPUTOS -PERU 138 - PERU 138     - CP: 3...
   5      ROSARIO - San Martin 715     - CP: 2000 - ROSA...
...                                                     ...
EO 13575  TOYOTA -MARTINEZ- - T. Edison 2659     - CP: 1...
   13576  BCO ITAU CASA CENTRAL - VICTORIA OCAMPO 360   ...
   13577  BCO ITAU SUC 5 BELGRANO - Av Cabildo 2215 - Be...
   13578  TOYOTA -MARTINEZ- - T. Edison 2659     - CP: 1...
   13579  BCO ITAU CASA CENTRAL - VICTORIA OCAMPO 360   ...

[52380 rows x 5 columns]

In [43]:
frames3=[t5,t6]
tdf2=pd.concat(frames3)
tdf2

              Nro AP  Posicion      Servicio                         Cliente  \
RO 0      40014546.0      20.0  4.001455e+09        Banco de Santa Cruz S.A.
   2      40014611.0      80.0  4.001461e+09     Petersen Thiele y Cruz S.A.
   3      40014862.0     100.0  4.001486e+10               TRANSFARMACO S.A.
   4      40015273.0      20.0  4.001527e+09  Nuevo Banco de Entre R¡os S.A.
   5      40017370.0      20.0  4.001737e+09    Nuevo Banco de Santa Fe S.A.
...              ...       ...           ...                             ...
EO 13575         NaN       NaN           NaN                             NaN
   13576         NaN       NaN           NaN                             NaN
   13577         NaN       NaN           NaN                             NaN
   13578         NaN       NaN           NaN                             NaN
   13579         NaN       NaN           NaN                             NaN

          Dia Pto Planif Recorrido   Horario  \
RO 0      NaN        NaN       NaN       NaN
   2      NaN        NaN       NaN       NaN
   3      NaN        NaN       NaN       NaN
   4      NaN        NaN       NaN       NaN
   5      NaN        NaN       NaN       NaN
...       ...        ...       ...       ...
EO 13575  5.0       A001    ITA006  10:00:00
   13576  5.0       A001    ITA010  19:45:00
   13577  NaN        NaN       NaN  00:00:00
   13578  1.0       A001    ITA006  10:00:00
   13579  1.0       A001    ITA010  19:45:00

                                                  Direccion
RO 0                                                    NaN
   2                                                    NaN
   3                                                    NaN
   4                                                    NaN
   5                                                    NaN
...                                                     ...
EO 13575  TOYOTA -MARTINEZ- - T. Edison 2659     - CP: 1...
   13576  BCO ITAU CASA CENTRAL - VICTORIA OCAMPO 360   ...
   13577  BCO ITAU SUC 5 BELGRANO - Av Cabildo 2215 - Be...
   13578  TOYOTA -MARTINEZ- - T. Edison 2659     - CP: 1...
   13579  BCO ITAU CASA CENTRAL - VICTORIA OCAMPO 360   ...

[104760 rows x 9 columns]

In [46]:
t5['Dia']=t6['Dia']
t5['Horario']=t6['Horario']
t5['Pto Planif']=t6['Pto Planif']
t5['Recorrido']=t6['Recorrido']
t5['Direccion']=t6['Direccion']
t5['Dia2']=t6['Dia']
t5

            Nro AP  Posicion     Servicio                         Cliente  \
RO 0      40014546        20   4001454620        Banco de Santa Cruz S.A.
   2      40014611        80   4001461180     Petersen Thiele y Cruz S.A.
   3      40014862       100  40014862100               TRANSFARMACO S.A.
   4      40015273        20   4001527320  Nuevo Banco de Entre R¡os S.A.
   5      40017370        20   4001737020    Nuevo Banco de Santa Fe S.A.
...            ...       ...          ...                             ...
EO 13575  40038816       600  40038816600            TOYOTA ARGENTINA S A
   13576  40038085       600  40038085600        BANCO ITAU ARGENTINA S A
   13577  40038088       600  40038088600        BANCO ITAU ARGENTINA S A
   13578  40038816       600  40038816600            TOYOTA ARGENTINA S A
   13579  40038085       600  40038085600        BANCO ITAU ARGENTINA S A

          Dia   Horario Pto Planif Recorrido  \
RO 0      5.0  16:45:00       A021    RGL001
   2      2.0  17:10:00       A001    CRS013
   3      1.0  16:00:00       A001    CRS041
   4      1.0  16:40:00       A020    PAR017
   5      3.0  01:55:00       A011    SFN009
...       ...       ...        ...       ...
EO 13575  5.0  10:00:00       A001    ITA006
   13576  5.0  19:45:00       A001    ITA010
   13577  NaN  00:00:00        NaN       NaN
   13578  1.0  10:00:00       A001    ITA006
   13579  1.0  19:45:00       A001    ITA010

                                                  Direccion  Dia2
RO 0      RIO GALLEGOS - Dr. Nestor C. Kirchner 812     ...   5.0
   2      Petersen Thiele y Cruz - CERRITO 740 1   - CP:...   2.0
   3      Transfarmaco S.A. (TIGRE 2) - MARCO SASTRE 108...   1.0
   4      CTRO COMPUTOS -PERU 138 - PERU 138     - CP: 3...   1.0
   5      ROSARIO - San Martin 715     - CP: 2000 - ROSA...   3.0
...                                                     ...   ...
EO 13575  TOYOTA -MARTINEZ- - T. Edison 2659     - CP: 1...   5.0
   13576  BCO ITAU CASA CENTRAL - VICTORIA OCAMPO 360   ...   5.0
   13577  BCO ITAU SUC 5 BELGRANO - Av Cabildo 2215 - Be...   NaN
   13578  TOYOTA -MARTINEZ- - T. Edison 2659     - CP: 1...   1.0
   13579  BCO ITAU CASA CENTRAL - VICTORIA OCAMPO 360   ...   1.0

[52380 rows x 10 columns]

In [47]:
t5['Tipo']='RO'
t5

            Nro AP  Posicion     Servicio                         Cliente  \
RO 0      40014546        20   4001454620        Banco de Santa Cruz S.A.
   2      40014611        80   4001461180     Petersen Thiele y Cruz S.A.
   3      40014862       100  40014862100               TRANSFARMACO S.A.
   4      40015273        20   4001527320  Nuevo Banco de Entre R¡os S.A.
   5      40017370        20   4001737020    Nuevo Banco de Santa Fe S.A.
...            ...       ...          ...                             ...
EO 13575  40038816       600  40038816600            TOYOTA ARGENTINA S A
   13576  40038085       600  40038085600        BANCO ITAU ARGENTINA S A
   13577  40038088       600  40038088600        BANCO ITAU ARGENTINA S A
   13578  40038816       600  40038816600            TOYOTA ARGENTINA S A
   13579  40038085       600  40038085600        BANCO ITAU ARGENTINA S A

          Dia   Horario Pto Planif Recorrido  \
RO 0      5.0  16:45:00       A021    RGL001
   2      2.0  17:10:00       A001    CRS013
   3      1.0  16:00:00       A001    CRS041
   4      1.0  16:40:00       A020    PAR017
   5      3.0  01:55:00       A011    SFN009
...       ...       ...        ...       ...
EO 13575  5.0  10:00:00       A001    ITA006
   13576  5.0  19:45:00       A001    ITA010
   13577  NaN  00:00:00        NaN       NaN
   13578  1.0  10:00:00       A001    ITA006
   13579  1.0  19:45:00       A001    ITA010

                                                  Direccion  Dia2 Tipo
RO 0      RIO GALLEGOS - Dr. Nestor C. Kirchner 812     ...   5.0   RO
   2      Petersen Thiele y Cruz - CERRITO 740 1   - CP:...   2.0   RO
   3      Transfarmaco S.A. (TIGRE 2) - MARCO SASTRE 108...   1.0   RO
   4      CTRO COMPUTOS -PERU 138 - PERU 138     - CP: 3...   1.0   RO
   5      ROSARIO - San Martin 715     - CP: 2000 - ROSA...   3.0   RO
...                                                     ...   ...  ...
EO 13575  TOYOTA -MARTINEZ- - T. Edison 2659     - CP: 1...   5.0   RO
   13576  BCO ITAU CASA CENTRAL - VICTORIA OCAMPO 360   ...   5.0   RO
   13577  BCO ITAU SUC 5 BELGRANO - Av Cabildo 2215 - Be...   NaN   RO
   13578  TOYOTA -MARTINEZ- - T. Edison 2659     - CP: 1...   1.0   RO
   13579  BCO ITAU CASA CENTRAL - VICTORIA OCAMPO 360   ...   1.0   RO

[52380 rows x 11 columns]